### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eeshankuic** [limikael/PixiTextInput#2]
Do you have a license you want to add to this? Is it MIT?

**Comment by limikael** [comment]
Haven't thought exactly of any license, so yes let's say MIT. At least let's say, it will be such a license that allows you to do whatever you want with it, and I hereby promise that I will never take any legal action against anyone using this source code for any purpose whatsoever.

This statement put here should be enough right? Or do we need some LICENSE.txt file or so?

The above statement does not require you to share any improvements you might add to this code. That being said, I know that there are improvements needed for this to reach a usable state. If you do add some usable stuff, I would encourage you to share them as a PR! Sharing code with the community is great fun, good karama, and rewarding in many ways, e.g. it is a good way to be visible to potential employers and other people who might want to work together with you... :)

**Comment by eeshankuic** [comment]
You'll need something that communicates the license. No license does not mean MIT/free to use. 

https://help.github.com/articles/open-source-licensing/

**Comment by limikael** [comment]
Alright, attached the MIT license. Hope it helps!
